# Generated by Django 4.2.1 on 2023-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=15)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('mob_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pic', models.ImageField(default='defaultUser.png', upload_to='customer_pics')),
            ],
        ),
    ]
