# Generated by Django 4.2.1 on 2023-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
