# Generated by Django 4.2.1 on 2023-06-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_measuring_unit_2_and_more'),
        ('purchase', '0004_alter_purchaseorderdescription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdescription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdescription',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_purchase_product', to='purchase.purchaseorder'),
        ),
    ]
