# Generated by Django 4.2.1 on 2023-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(default='defaultProduct.png', upload_to='product_pics')),
                ('hsn_code', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('min_stock_alarm', models.IntegerField(default=20)),
                ('measuring_unit_1', models.CharField(max_length=20)),
                ('measuring_unit_2', models.CharField(blank=True, max_length=20, null=True)),
                ('measuring_unit_relation', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('gst', models.IntegerField()),
            ],
        ),
    ]
