# Generated by Django 4.2.1 on 2023-06-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty_actual',
            new_name='qty',
        ),
    ]
