# Generated by Django 4.2.1 on 2023-07-11 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sale.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_sale_type', models.CharField(choices=[('1', 'Intra-State (SGST & CGST)'), ('2', 'Intra-State (UTGST)'), ('3', 'Inter-State (IGST)')], default=1, max_length=10)),
                ('unreg_bill_to_name', models.CharField(blank=True, max_length=50, null=True)),
                ('unreg_bill_to_address1', models.CharField(blank=True, max_length=50, null=True)),
                ('unreg_bill_to_address2', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_address1', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_address2', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_ship_to_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_name', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_veh_no', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('order_price', models.FloatField()),
                ('amount_paid', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saleorder_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('reg_bill_to', models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_del_customer), to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('sell_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('taxable_value', models.FloatField()),
                ('gst_value', models.FloatField()),
                ('product_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='sale.saleorder')),
            ],
        ),
        migrations.AddField(
            model_name='saleorder',
            name='unreg_bill_to_state',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bill_to_sale_order', to='sale.state'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='unreg_ship_to_state',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ship_to_sale_order', to='sale.state'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saleorder_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
