# Generated by Django 4.2.1 on 2023-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='order_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
