# Generated by Django 4.2.1 on 2023-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='pay_status',
            field=models.CharField(choices=[('1', 'Unpaid'), ('2', 'Due'), ('3', 'Partial'), ('4', 'Paid')], default=1, max_length=10),
        ),
    ]
