# Generated by Django 4.2.1 on 2023-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_saleorder_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='gst_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='qty',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
