# Generated by Django 4.2.1 on 2023-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleorder_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='amt_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='pay_status',
            field=models.CharField(choices=[('1', 'Unpaid'), ('3', 'Partial'), ('4', 'Paid')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='saleorderdescription',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
