# Generated by Django 4.2.1 on 2023-07-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_saleorder_amt_paid_alter_saleorder_pay_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='pay_status',
        ),
    ]
